services:
  api:
    build:
      context: ./BE
      dockerfile: ./Dockerfile
    image: deejtsn/private:chores_api_v1
    volumes:
      - ./BE/data:/app/data            # Mount host folder for persistence
    environment:
      DB_PATH: "/app/data/database.db"
    platform: linux/amd64  
    ports:
      - "8000:8000"
    restart: always